добавил три файла с заданиями  в папке HW_3
andreyknyshov/Js_hw pull request #1
Opened 2024-05-23 07:30 UTC by andreyknyshov

2024-05-23 12:52 UTC, anatoly-karpovich requested changes

2024-05-23 12:52 UTC, anatoly-karpovich commented on HW_3/hw_3.2.js
> +let discriminant = b ** 2 - 4 * a * c;
const will be better

2024-05-23 12:52 UTC, anatoly-karpovich commented on HW_3/hw_3.2.js
> +let discriminant2 = b2 ** 2 - 4 * a2 * c2;
const will be better

2024-05-23 12:52 UTC, anatoly-karpovich commented on HW_3/hw_3.3.js
> +let nnnString = nString + nString + nString;
const will be better

2024-05-24 07:47 UTC, VladimirLQA approved these changes
Well done

2024-05-24 08:11 UTC, anatoly-karpovich approved these changes

2024-05-24 08:22 UTC, merged