Hw_4
andreyknyshov/Js_hw pull request #2
Opened 2024-05-26 20:28 UTC by andreyknyshov

please approve my HW_4

2024-05-26 21:24 UTC, VladimirLQA approved these changes

2024-05-26 21:24 UTC, VladimirLQA commented on HW_4/hw_4.2.3.js
> +  if (isNaN(age) != true) {
```suggestion
  if (!isNaN(age)) {
```

2024-05-26 21:24 UTC, VladimirLQA commented on HW_4/hw_4.3.js
> +if (isNaN(age) || (age < 1)) {
```suggestion
if (isNaN(age)) {
```

2024-05-26 22:24 UTC, anatoly-karpovich requested changes

2024-05-26 22:24 UTC, anatoly-karpovich commented on HW_4/hw_4.2.2.js
> +if (typeof(age) != 'number') {
Better make like this:
```
if (typeof(age) != 'number') {
console.log('Check the value of the ‘age’ variable. The required data type is a number');
} else {
  if (age < age_2) { 
     console.log('You don’t have access cause your age is ' + age + ' It’s less then '); 
    } else if ((age >= age_2) && (age < age_3)) { 
    console.log('Welcome  !'); 
    } else if (age > age_3) { 
     console.log('Keep calm and look Culture channel'); 
    } else console.log('Technical work'); 
}
```

2024-05-27 06:46 UTC, andreyknyshov commented on HW_4/hw_4.2.2.js
> +if (typeof(age) != 'number') {
ok. done

2024-05-27 07:02 UTC, andreyknyshov commented
made the corrections from the mentor

2024-05-27 09:12 UTC, anatoly-karpovich approved these changes

2024-05-27 18:20 UTC, merged