add HW_6
andreyknyshov/Js_hw pull request #4
Opened 2024-06-03 21:26 UTC by andreyknyshov

Прошу проверить ДЗ №6

2024-06-03 23:11 UTC, anatoly-karpovich requested changes

2024-06-03 23:11 UTC, anatoly-karpovich commented on HW_5/hw_5.2.1.js
> +while (bytes >= 1024) {
no check for currentUnit > 3

2024-06-03 23:11 UTC, anatoly-karpovich commented on HW_6/hw_6.1.js
> +    return null;
```suggestion
    return resultArray.length ? resultArray : null
```

2024-06-03 23:11 UTC, anatoly-karpovich commented on HW_6/hw_6.2.1.js
> +    for (let indexComp = 0; indexComp < competitorPizzas.length; indexComp++) {
use .includes() instead of nested loop

2024-06-03 23:11 UTC, anatoly-karpovich commented on HW_6/hw_6.2.3.js
> +    }
```suggestion
for(const num of number) {
  if(!uniqueNumbers.includes(num)) {
    uniqueNumbers.push(num)
  }
}
```

2024-06-04 06:53 UTC, VladimirLQA approved these changes

2024-06-04 06:53 UTC, VladimirLQA commented on HW_6/hw_6.2.4.js
> +function Palindrome(word) {
```suggestion
function palindrome(word) {
```

Function names start in lower case, upper case is used for `constructor functions`

2024-06-05 21:21 UTC, andreyknyshov commented
changed according to the mentors' comments

2024-06-10 17:25 UTC, anatoly-karpovich approved these changes

2024-06-10 17:25 UTC, anatoly-karpovich commented on HW_6/hw_6.1.js
> +}
```suggestion
 return index === -1 ? null : [employeeName, paymentArray[index]];
}
```

2024-06-10 18:22 UTC, merged